version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file LambdaCDDemo-master/samTemplate.yaml --s3-bucket caninicfsambucket --output-template-file LambdaCDDemo-master/outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
